services:
  translation-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      # This now reads the WORKERS variable from your shell.
      # It defaults to 1 if the variable isn't set.
      - WORKERS=${WORKERS:-1}
    volumes:
      # Mounts your local server directory into the container for live updates.
      - .:/app
    # restart upon reboot
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
